//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smkstudentbaru
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guru()
        {
            this.Kelas = new HashSet<Kela>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
        public string No_Telepon_id { get; set; }
        public int Mata_pelajaran_id { get; set; }
    
        public virtual Mapel Mapel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kela> Kelas { get; set; }
    }
}
