//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smkstudentbaru
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbsmkrtudentbaruEntities : DbContext
    {
        public dbsmkrtudentbaruEntities()
            : base("name=dbsmkrtudentbaruEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Guru> Gurus { get; set; }
        public virtual DbSet<Jurusan> Jurusans { get; set; }
        public virtual DbSet<Kela> Kelas { get; set; }
        public virtual DbSet<Mapel> Mapels { get; set; }
        public virtual DbSet<Siswa> Siswas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
