//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smkstudentbaru
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siswa
    {
        public int ID { get; set; }
        public string Nama { get; set; }
        public System.DateTime Tanggal_lahir { get; set; }
        public string NISN { get; set; }
        public string No_Telepon { get; set; }
        public string Orang_tua { get; set; }
        public int Jurusan_id { get; set; }
        public int Kelas_id { get; set; }
    
        public virtual Jurusan Jurusan { get; set; }
        public virtual Kela Kela { get; set; }
    }
}
